#!/bin/sh

BASE_DIR=$(cd "$(dirname "$0")" && pwd)
VENV_DIR="$BASE_DIR/.venv"

echo "Started installation"

if [ -d "$VENV_DIR" ]; then
  echo "Found a vitrual environment. Removing existing one."
  rm -rf "$VENV_DIR"
fi

echo "Setting up python virtual environment"
python3 -m venv "$VENV_DIR"

echo "Setting permissions"
chmod a=rx "clean"
chmod a=rx "safe-pm"
chmod a=rx "install"

# If requirements.txt does not exist, we are done.
if [ -f "requirements.txt" ]; then
  if [ -d "$VENV_DIR" ]; then

    echo "Installing dependencies"

    # Activate python virtual environment
    source "$VENV_DIR/bin/activate"

    # Install dependencies
    pip install -r "requirements.txt"

    # Deactivate virtual environment
    deactivate
  else
    echo "Installation failed; Python environment could not be setup properly"
    exit 1
  fi
fi

SHELL_NAME=$(basename "$SHELL")
case "$SHELL_NAME" in
"bash")
  RC_FILE="$HOME/.bashrc"
  ;;
"zsh")
  RC_FILE="$HOME/.zshrc"
  ;;
"fish")
  RC_FILE="$HOME/.config/fish/config.fish"
  ;;
esac

if [ -f "$RC_FILE" ]; then
  echo $BASE_DIR
  echo "Setting environment PATH variable"
  echo "export PATH=\$PATH:$BASE_DIR" >>"$RC_FILE"
  echo "Installation successful. You can now use 'safe-pm --help' in a new terminal window."
else
  echo "$RC_FILE not found."
  echo "Please set the PATH variable manually by appending below line in your shell's .*rc file."
  echo "export PATH=\$PATH:$BASE_DIR"
fi
