#!/bin/sh

BASE_DIR=$(cd "$(dirname "$0")" && pwd)
VENV_DIR="$BASE_DIR/venv"

if [ -d "$VENV_DIR" ]; then
  # Activate python virtual environment
  source "$VENV_DIR/bin/activate"

  # Execute the script passed as param
  python "$BASE_DIR/bin/main.py" ${@:1}
  EXIT_CODE=$?

  # Deactivate virtual environment
  deactivate

  exit $EXIT_CODE
else
  echo "Python environment is not setup. Please run \`install\` first".
  exit 103
fi